### ISSUE TITLE
bug(resourceExtractor): Long S3 bucket names generate invalid partial ARNs

### ISSUE THREAD

**Issue by maafk** [cdklabs/cdk-enterprise-iac#130]
### What is the problem?

The [S3 default transformer](https://github.com/cdklabs/cdk-enterprise-iac/blob/d1ad4425a01ef18d52c219ffaaa7a13c0d32d184/src/patches/resource-extractor/resourceTransformer.ts#L129) doesn't handle long stack/bucket names appropriately

### Reproduction Steps

```typescript
import { App, Aspects, Stack } from 'aws-cdk-lib';
import { ResourceExtractor } from '@cdklabs/cdk-enterprise-iac';
import { Code, Function, Runtime } from 'aws-cdk-lib/aws-lambda';
import { Bucket } from 'aws-cdk-lib/aws-s3';

const app = new App();
const stack = new Stack(app, 'LongBucketStackWithASuperLongNameHolyCowThatsAPrettyLongStackNameWhoaTherePartner');

const extractedStack = new Stack(app, 'extractedStack')
const bucket = new Bucket(stack, 'ThisBucketIdIsSeriouslySoLongThatItExceedsSomeSetLimitForCloudformation')
const fn = new Function(stack, "MyFunction", {
  code: Code.fromInline('def handler(event, context):\n    print(event)'),
  runtime: Runtime.PYTHON_3_9,
  handler: 'index.handler',
})

bucket.grantReadWrite(fn)
const synthed_app = app.synth()
Aspects.of(app).add(new ResourceExtractor({
  stackArtifacts: synthed_app.stacks,
  resourceTypesToExtract: [
    'AWS::IAM::Role',
    'AWS::IAM::Policy',
    'AWS::IAM::ManagedPolicy',
    'AWS::IAM::InstanceProfile',
  ],
  extractDestinationStack: extractedStack
}))
app.synth({force: true});
```

Synthesize to files using

```zsh
cdk synth extractedStack > extracted.yml && cdk synth LongBucketStackWithASuperLongNameHolyCowThatsAPrettyLongStackNameWhoaTherePartner >> long_bucket.yml
```
The policy inside `extracted.yml` contains the following

```yaml
Resource:
  - Fn::Join:
      - ""
      - - "arn:"
        - Ref: AWS::Partition
        - :s3:::longbucketstackwithasuperlongnameholycowthatsaprettylongstacknamewhoatherepartner-thisbucketidisseriouslysolongthatitexceedssomesetlimitforcloudformationd5c293f8*
```

However the S3 bucket created by Cloudformation has the name `longbucketstackwithasupe-thisbucketidisseriouslys-19zd4povz2415`

### What did you expect to happen?

Expected the S3 bucket ARN in the extracted IAM policy to be valid

### What actually happened?

The generated resource ARN doesn't match the bucket that was created

### cdk-enterprise-iac version

0.0.102

### Language

Typescript
