### ISSUE TITLE
bug: Static Resource Arns

### ISSUE THREAD

**Issue by newcmitc-aws** [cdklabs/cdk-enterprise-iac#158]
### What is the problem?

In particular, this is for working with S3. When setting a static S3 Bucket Name, it's arn is falsely represented in the extracted stack

### Reproduction Steps

```typescript
#!/usr/bin/env node
import { App, Aspects, RemovalPolicy, Stack } from 'aws-cdk-lib';
import { Code, Function, Runtime } from 'aws-cdk-lib/aws-lambda';
import { Bucket } from 'aws-cdk-lib/aws-s3';
// Import ResourceExtractor
import { ResourceExtractor } from '@cdklabs/cdk-enterprise-iac';

const app = new App();
const appStack = new Stack(app, 'MyAppStack');
// Set up a destination stack to extract resources to
const extractedStack = new Stack(app, 'ExtractedStack');

const func = new Function(appStack, 'TestLambda', {
  code: Code.fromInline('def handler(event, context):\n    print(event)'),
  handler: 'index.handler',
  runtime: Runtime.PYTHON_3_9,
});
const bucket = new Bucket(appStack, 'TestBucket', {
  bucketName:"static-bucket-name",
  autoDeleteObjects: true,
  removalPolicy: RemovalPolicy.DESTROY,
});
bucket.grantReadWrite(func);

// Capture the output of app.synth()
const synthedApp = app.synth();
// Apply the ResourceExtractor Aspect
Aspects.of(app).add(
  new ResourceExtractor({
    // synthesized stacks to examine
    stackArtifacts: synthedApp.stacks,
    // Array of Cloudformation resources to extract
    resourceTypesToExtract: [
      'AWS::IAM::Role',
      'AWS::IAM::Policy',
      'AWS::IAM::ManagedPolicy',
      'AWS::IAM::InstanceProfile',
    ],
    // Destination stack for extracted resources
    extractDestinationStack: extractedStack,
  })
);
// Resynthing since ResourceExtractor has modified the app
app.synth({ force: true });
```

### What did you expect to happen?

Goal was to separate out IAM permissions with proper reference to the S3 bucket name

### What actually happened?

The ARN for the S3 bucket in the IAM Role is incorrect. (Should be "static-bucket-name" but got "myappstack-testbucket560b80bc" )
```yaml
TestLambdaServiceRoleDefaultPolicy0F2D5E78:
  Type: AWS::IAM::Policy
  Properties:
    PolicyDocument:
      Statement:
        - Action:
            - s3:GetObject*
            - s3:GetBucket*
            - s3:List*
            - s3:DeleteObject*
            - s3:PutObject
            - s3:PutObjectLegalHold
            - s3:PutObjectRetention
            - s3:PutObjectTagging
            - s3:PutObjectVersionTagging
            - s3:Abort*
          Effect: Allow
          Resource:
            - Fn::Join:
                - ""
                - - "arn:"
                  - Ref: AWS::Partition
                  - :s3:::myappstack-testbucket560b80bc*
            - Fn::Join:
                - ""
                - - Fn::Join:
                      - ""
                      - - "arn:"
                        - Ref: AWS::Partition
                        - :s3:::myappstack-testbucket560b80bc*
                  - /*
      Version: "2012-10-17"
```

### cdk-enterprise-iac version

0.0.126

### Language

Typescript

### Other information

This is likely caused as `bucket.bucketArn` and `bucket.bucketName` are both tokens.

If anyone is encountering this issue, there are a few workarounds:
- Don't specify the `bucketName` parameter, allowing CDK to set it's default
- Manually define IAM permissions in CDK, statically typing the resource arn there as well
- Add AWS::S3::Bucket to the extract list as well. Other stacks will reference the value via CFN_Output variables
